"""remove justification from amendment

Revision ID: 0aabb8ceed74
Revises: 8bbaa605220f
Create Date: 2025-06-06 03:05:29.808855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aabb8ceed74'
down_revision = '8bbaa605220f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('amendment', schema=None) as batch_op:
        batch_op.drop_column('justification')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('amendment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('justification', sa.TEXT(), nullable=False))

    # ### end Alembic commands ###
