"""Ajout legal_element_id à Amendment

Revision ID: 597015a05227
Revises: 0aabb8ceed74
Create Date: 2025-06-12 18:06:35.285612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '597015a05227'
down_revision = '0aabb8ceed74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('amendment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('legal_element_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_amendment_legal_element', 'legal_element', ['legal_element_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('amendment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_amendment_legal_element', type_='foreignkey')
        batch_op.drop_column('legal_element_id')

    # ### end Alembic commands ###
