"""Add paragraph_index and type to Amendment

Revision ID: 8b0f7ed63553
Revises: 
Create Date: 2025-06-05 16:34:35.162981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b0f7ed63553'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('amendment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paragraph_index', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('amendment', schema=None) as batch_op:
        batch_op.drop_column('type')
        batch_op.drop_column('paragraph_index')

    # ### end Alembic commands ###
